spring:
  datasource:
    username: postgres
    password: ld2erw71904
    url: jdbc:postgresql://localhost:5432/shopdb
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  flyway:
    schemas:
    - shop
    default-schema: shop